--COMENTARIOS

-- SQL NÃO É UMA LINGUAGEM CASE SENSITIVE
-- É COSTUME ESCREVER EM CAIXA ALTA

-- COMANDOS DO SQL --> CAIXA ALTA
-- COMANOS NÃO REFERENTES AO SQL --> caixa baixa

--APAGANDO UM BANCO DE DADOS
DROP DATABASE agenda;

-- CRIANDO UM BANCO DE DADOS
CREATE DATABASE agenda;

--CONECTAR AO BANCO DE DADOS
CONNECT agenda;

--DENTRO DE UMA TABELA SO PODE EXISTIR UMA UNICA CHAVE PRIMARIA
-- OS DADOS SAO ARMAZENADOS EM FORMATO DE TABELA
MATRICULA	NOME	EMAIL				ENDERECO
1001		JUCA	JUCA@EMAIL.COM		RUA ABC
1002		ANA		ANA@EMAIL.COM		AVENIDA X
1003		ANA		ANA@EMAIL.COM		AVENIDA X
1004		ANA		ANA@EMAIL.COM		AVENIDA X
1005		ANA		ANA@EMAIL.COM		AVENIDA X

--CONTATOS
	-- ID			(INTEIRO) CHAVE PRIMARIA (PK)
	-- NOME			(TEXTO)
	-- EMAIL		(TEXTO)
	-- TELEFONE		(TEXTO)
	-- DT NASC		(DATA)

--SOMENTE NO MYSQL AUTO_INCREMENT
-- PK AUTOMATICANTE É UNIQUE E NOT NULL
CREATE TABLE contatos(
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	telefone CHAR(11) NOT NULL,
	dt_nasc DATE NULL
);

-- EXIBE TODAS AS TABELAS DO BANCO DE DADOS ATUAL
SHOW TABLES;

-- EXIBE TODAS OS DATABASES
SHOW DATABASES;

-- OPERAÇÕES DE BANCO DE DADOS
	--INSERT
	--SELECT
	--UPDATE
	--DELETE

--PARA DATAS --> ANO/MES/DIA --> YYYY/MM/DD
--INSERIR UM CONTATO NA TABELA contatos
--'STRINGS' SAO PASSADAS COM ASPAS SIMPLES

INSERT INTO contatos (nome, email, telefone, dt_nasc)
VALUES ('Juca', 'juca@email.com', '21987654321', '2020/09/10');

INSERT INTO contatos (nome, email, telefone, dt_nasc)
VALUES ('Juca', 'juca123@email.com', '21987654321', '2020/09/10');

INSERT INTO contatos (nome, email, telefone, dt_nasc)
VALUES ('Gigi', 'gigi@email.com', '21999654321', '2010/03/21');

INSERT INTO contatos (nome, email, telefone, dt_nasc)
VALUES ('Gabi', 'gabi@email.com', '21999654321', '2010/03/21');

--CONSULTAR OS DADOS NA TABELA contatos
SELECT * FROM contatos;

-- APAGAR UM REGISTRO *******CUIDADO********* 
DELETE FROM contatos WHERE id = 4;
DELETE FROM contatos WHERE nome = 'Juca';

-- ALTERAR UM REGISTRO *******CUIDADO********* 
UPDATE contatos
SET email = 'juquinha@globo.com', dt_nasc = '1990/02/10'
WHERE id = 8;

UPDATE contatos
SET email = 'juca@email.com', dt_nasc = '1990/02/10'
WHERE id = 8;











